### ISSUE TITLE
App checking for the external app exiftool

### ISSUE THREAD

**Issue by waldirio** [MultiMedia-Management/media-organizer#18]
required once we are using a library that will call the external app. Testing in a fresh machine without this app and check the behavior.

**Comment by marcellestp** [comment]
Below, we can see the missing package on windows box
```
Traceback (most recent call last):
  File "C:\code\media-organizer\mo.py", line 9, in <module>
    parse.main()
  File "c:\code\venv\media-organizer\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\venv\media-organizer\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "c:\code\venv\media-organizer\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\venv\media-organizer\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\venv\media-organizer\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\venv\media-organizer\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\media-organizer\parse\parse.py", line 79, in source_dir
    execution.import_content(src_dir)
  File "C:\code\media-organizer\execution\execution.py", line 50, in import_content
    import_videos(SOURCE_FILE_PATH)
  File "C:\code\media-organizer\execution\execution.py", line 69, in import_videos
    with exiftool.ExifToolHelper() as et:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\code\venv\media-organizer\Lib\site-packages\exiftool\helper.py", line 101, in __init__
    super().__init__(**kwargs)
  File "c:\code\venv\media-organizer\Lib\site-packages\exiftool\exiftool.py", line 300, in __init__
    self.executable = executable or constants.DEFAULT_EXECUTABLE
    ^^^^^^^^^^^^^^^
  File "c:\code\venv\media-organizer\Lib\site-packages\exiftool\exiftool.py", line 374, in executable
    raise FileNotFoundError(f'"{new_executable}" is not found, on path or as absolute path')
FileNotFoundError: "exiftool.exe" is not found, on path or as absolute path
```
